
//Crear
###
POST http://localhost:4000/api/horarioDia/
Content-Type: application/json

{
"dia": "Jueves",
"entrada": "7:00 am",
"salida": "4:00 pm",
"semana_horario": "dsjhu93434huerf"
}

//Get
###
GET http://localhost:4000/api/horarioDia/632fb2762ae3057679023003

//Get All
###
GET http://localhost:4000/api/horarioDia/


//Eliminar
###
DELETE http://localhost:4000/api/horarioDia/632fb2762ae3057679023003


//Update
###
PUT http://localhost:4000/api/horarioDia/632fb2722ae3057679023001
Content-Type: application/json

{
 "salida": "3:00 pm"
}
