
//Crear
###
POST http://localhost:4000/api/protocolo/
Content-Type: application/json

{
"cod_protocolo": "cd-002",
"encargado": "sod39sdfsd",
"alumno": "dnf83wsdf",
"responsable": "nsd834rhsdf"
}

//Get
###
GET http://localhost:4000/api/protocolo/632fb925104e093cd03fd2f3

//Get All
###
GET http://localhost:4000/api/protocolo/


//Eliminar
###
DELETE http://localhost:4000/api/protocolo/632fb92e104e093cd03fd2f7


//Update
###
PUT http://localhost:4000/api/protocolo/632fb925104e093cd03fd2f3
Content-Type: application/json

{
 "encargado": "b4dfgh88"
}
