import mongoose from 'mongosee';
const { Schema } = mongoose;

const PersonalSchema = new mongoose.Schema({
    PrimerApellido: String,
    SegundoApellido: String,
    Nombre: String,
    Cédula: String,
    Estado: String,
    Telefono: String,
    GrupoProfesional: String,
    FechaDeNacimiento: String,
    Provincia: String,
    Cantón: String,
    Distrito: String,
    Barrio: String,
    DirecciónExacta: String,
    CorreoMEP: String,
    CorreoElectrónico: String,
    Puesto: String,
    CondiciónDelNombramiento: String,
    InstituciónDondeCompleta: String,
    HorarioDondeCompleta: String,
    SindicatosQuePertenece: String,
    AñosDeServicio: String,
    AñosExperienciaEspecífica: String,
    ÚltimoGradoAcadémico: String,
    CalificacionesExelentes: String,
    PuntosCarrera: String,
    NombreCompleto: String,
    DatosAdjuntos: String,
    DetalleTítulos: String,
    LugarDeNacimiento: String,
    Nacionalidad: String,
    Género: String,
    Sexo: String,
    ContactoParaEmergencia: String,
    TeléfonoEmergencia1: String,
    LE: Date,
    LS: Date,
    KE: Date,
    KS: Date,
    ME: Date,
    MS: Date,
    JE: Date,
    JS: Date,
    VE: Date,
    VS: Date,
    LeccionesGuia: String,
    ComitedeEvaluación: String,
    ComitedeApoyo: String,
    OtrosComitesOpcion1: String,
    OtrosComitesOpcion2: String
});

export default mongoose.model("Personal", PersonalSchema);