###
POST http://localhost:4000/api/estudiantes/crearEstudiante
Content-Type: application/json

{
"PrimerApellido": "kendall", 
"SegundoApellido": "Granados", 
"Nombre": "Kendall", 
"Nivel": "Noveno",
"Seccion":"9-2",
"Adecuacion": false,
"Cursolectivo":"2018",
"RecibeReligión": true,
"RepiteCursoLectivo": true,
"CuentaconbeneficiodeBeca":true,
"Institucióndeprocedencia": "Pedregal",
"PoseeDispositivosElectrónicos": true,
"TieneConectividad": false,
"Estado": true,
"Modalidad": "Presencial"
}

###
GET http://localhost:4000/api/estudiante
Content-Type: application/json

{
    "cedula":"sdfs"
}

###
PUT http://localhost:4000/api/estudiante
Content-Type: application/json

{
"idPersonaje": 1,
"cedula": "hgjhg"
}

###
GET http://localhost:4000/api/estudiantes/62f33754162cbe1de9cbe278
