###
POST http://localhost:4000/api/persona
Content-Type: application/json

{
"Nombre": "kendall", 
"Apel1": "granados", 
"Apel2": "barrantes", 
"cedula": "1175207",
"Apel1": "granados",
"Apel2": "barrantes",
"Direccion_id_Direccion":1,
"Nombre": "kendall",
"Roll_idRol":1,
"cedula": "1175207",
"contacto": "86342267",
"edad":22,
"email": "kendall24gb@gmail.com",
"genero": "Masculino",
"nacionalidad": "tico",
"sexo": "Masculino"
}

###
GET http://localhost:4000/api/estudiante
Content-Type: application/json

{
    "cedula":"sdfs"
}

###
PUT http://localhost:4000/api/estudiante
Content-Type: application/json

{
"idPersonaje": 1,
"cedula": "hgjhg"
}